version: '3.8'
services:
  app:
    image: php:8.2-apache
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_NAME=event_db
      - DB_USER=root
      - DB_PASS=secret
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=event_db
    ports:
      - "3306:3306"